### ISSUE TITLE
Søgning og brug af suggestion funker ikke når man bruger mus

### ISSUE THREAD

**Issue by fvsdbc** [DBCDK/tanterne#102]
prøv at skrive hunde og klik på hundestejler ... bruger man tastatur er det ok.

**Comment by hrmoller** [comment]
Kan ikke reproducere på touch pad.

**Comment by fvsdbc** [comment]
Hvis man fx i søgefeltet skriver hun kommer der flere forslag. Når jeg i Chrome klikker på en af dem sker der ingentig. Bruger jeg tastatur og vælger med pil-taster og retur, funker det ok.

**Comment by hrmoller** [comment]
Lad os lige kigge på den her fredag. Jeg kan ikke reproducere den på min laptop...
