### ISSUE TITLE
Job på dbclib systemet som dumper dk5

### ISSUE THREAD

**Issue by fvsdbc** [DBCDK/tanterne#12]
Kan gøres i stil med:

setenv NLS_LANG AMERICAN_DENMARK.WE8ISO8859P1
dump_v3 <user>/<password>@<some.db>.dbc.dk | marcunicode > dk5_total.iso2709

bruger og passwd kan får af FVS eller AF

**Comment by KiraH** [comment]
nyt dk5 dump hentes hver gang jobbet køres på isen.
