### ISSUE TITLE
PRO: Genvejstaster

### ISSUE THREAD

**Issue by fvsdbc** [DBCDK/tanterne#167]
Tilbage til start, til søgefelt, tøm kurv (er vel identisk med tilbage til start)

**Comment by fvsdbc** [comment]
H for home (tilbage til start) og S for Search/Søg

**Comment by KiraH** [comment]
- Genvejstast til "tøm kurv" mangler
- Ingen af genvejstasterne virker i min firefox
- genvejstasten til home virker ikke i IE

**Comment by fvsdbc** [comment]
... og T for Tøm kurv
