### ISSUE TITLE
kan ikke fremsøge 99.4

### ISSUE THREAD

**Issue by KiraH** [DBCDK/tanterne#215]
Der kommer ikke noget når man søger på 99.4, men man kan finde den hvis man navigerer i hierakiet.

**Comment by KiraH** [comment]
Heller ikke 19.6 og 07

**Comment by fvsdbc** [comment]
Situationen opstod når en registerpost indeholder et dk5 tal i 652m, hvor den tilhørende systematikpost ikke kan findes:
99.4 findes sammen med 99.332 i "Politikere", mens 99.332 systematikposten er ignoreret fordi den ikke har noget d09 *a
19.6 og 07 fejler da registerposten "Informationsteknologi", indeholder "19.6 1" i 652 *m

**Comment by BirgitG** [comment]
Så er 99.4 m.fl. søgbare til gengæld har vi mistet et væld af andre Blandt de øverst 50-59 og 70-79 blandt de næste f. ex. 29 og 36 videre ned f.eks. 62.3, 62.8 og 62.9 og rigtigt mange flere.
Dannes hierarkiet ud fra registerposterne? - det virker usikkert

**Comment by fvsdbc** [comment]
Nej, Hierarkiet dannes af systematik-posterne og register-posterne bruger så hierarkiet. Jeg har ingen problemer med 29, 36 eller nogen af de andre?

**Comment by BirgitG** [comment]
Hej Finn
Nedenstående har jeg søgt 36 og kommer ind i register ikke som normalt i den systematiske. På skærmbilledet til højre kan du se, at 36 mangler – og se også den amputerede 50-59

[cid:image003.jpg@01D2DAC6.BC041690]


Fra: Finn Stausgaard [mailto:notifications@github.com]
Sendt: 1. juni 2017 10:54
Til: DBCDK/tanterne <tanterne@noreply.github.com>
Cc: Birgit Gøtterup <BG@dbc.dk>; Comment <comment@noreply.github.com>
Emne: Re: [DBCDK/tanterne] kan ikke fremsøge 99.4 (#215)


Nej, Hierarkiet dannes af systematik-posterne og register-posterne bruger så hierarkiet. Jeg har ingen problemer med 29, 36 eller nogen af de andre?
