### ISSUE TITLE
søgeresultat - match på søgeordet ønskes øverst

### ISSUE THREAD

**Issue by KiraH** [DBCDK/tanterne#216]
Sortering
Det ville være dejligt, hvis det ord, som rammer præcist (hverken mere eller mindre), det man har søgt på og som stammer fra 610/630/633/640, er placeret øverst og øvrige hit kommer alfabetiseret. 
Prøv f.eks. at søge på ’uddannelsespolitik’ – det centrale hit skal man scrolle for at se.

**Comment by kkdbc** [comment]
fvs vurderer hvor dyr den er

**Comment by vibjerg** [comment]
Result needs to be sorted by title instead of index
