### ISSUE TITLE
Klikbare ord i søgeresultat

### ISSUE THREAD

**Issue by KiraH** [DBCDK/tanterne#219]
Jeg mener, at jeg tidligere har kunnet klikke på de enkelte ord i søgeresultatet og få vist hele registerindgangen med aspekter. Ordene er ikke klikbare længere.

**Comment by kkdbc** [comment]
kommer ikke med i 1.version

**Comment by fvsdbc** [comment]
Det er kun på hierarki siden at de er klikbare og nu visuelt sådan - #243

**Comment by fvsdbc** [comment]
Closed
