### ISSUE TITLE
registerposter ved søgning skal altid vises i sin helhed

### ISSUE THREAD

**Issue by KiraH** [DBCDK/tanterne#220]
Hvis man søger på sygdom er det ikke nok, at få vist f.eks. 

Bidfunktion, se 61.27 Muskel- og knoglefysiologi. Bevægelseslære

Der er jo søgt på ’sygdomme’ og sygdomme, der rammer bidfunktionen står ikke i 61.27. Hvis den fulde registerpost blev vist, ville man blive klogere:
Fra dk5web:
bidfunktion 61.27
bidfunktion (sygdomme) 61.8

Konklusionen må være, at registerposter ved søgning altid skal vises i deres helhed. Ellers bliver der misforståelser.
(Dog er det ok kun at vise opslagsordet, når man er inde i hierarkiet – hvis det er tydeligt, at ordene er klikbare).

De felter, der skal vises er: 
610/630/633/640(, se 652 m/n/d/g u-hentet fra systematikpost)
(651)
•	(b00 a b)
•	(b52 y, se m/d u-hentet fra systematikpost)
(b51a b med samme indhold i *å som ovenstående b52)
•	 (b52 y, se m/d u-hentet fra systematikpost)
(b51a b med samme indhold i *å som ovenstående b52)
•	…

() betyder, at felterne ikke altid findes – hvor der ikke er specificeret delfelter er det alle delfelter.
Jeg har ingen religion i ’klat’ eller andre underordnings/gentagelsestegn eller for den sags skyld gentagelse af opslagsordet som i dk5web.

**Comment by kkdbc** [comment]
får vi for få data med ud?

**Comment by vibjerg** [comment]
Hvis der kun var et registerord i et søgeresultat blev det ikke vist. Det er nu lavet om. De andre informationer bliver vist under systematikken.

**Comment by vibjerg** [comment]
Den historiske note skal vises på registerposter og registerord
