### ISSUE TITLE
valgfrie grupper

### ISSUE THREAD

**Issue by KiraH** [DBCDK/tanterne#222]
Valgfrie grupper
Vi har nogle grupper, som ikke bruges her i huset, men er valgfrie. De er med i hierarkiet på lige fod med de almindelige grupper, men er i den trykte udgave markeret med indramning med en enkelt streg:

Der er tale om 35 grupper, så jeg tænker, at jeg vil tilføje ’ - valgfri gruppe’ til overskriften i systematikposterne 652u, så det kommer med ud, når man søger i systematikken. Men det vil nok være forvirrende i den brugerrettede udgave, - så måske kan vi udelade disse 35 poster fra den brugerrettede udgave??? – der vil ikke være registerposter, som henviser til disse grupper. Posterne kan søges entydigt ved at de alle, og kun de har teksten ’valgfri gruppe’ i første a40-felt. De har også klassemærket i 652*n, men det er der også en række andre poster, der har.

**Comment by kkdbc** [comment]
vi opretter fake registerposter hvis vi har en systematik-poster uden tilhørende registerpost. Man søger ikke i systematikposter - de bruges til at danne hieraki.

**Comment by fvsdbc** [comment]
Valgfrie grupper (i alt 35 stk) er grupper, som lokalhistoriske samlinger har ønsket oprettet, men som ikke er del af det egentlige dk5, og som derfor ikke findes på hylderne i biblioteket. Grupperne kan findes entydigt, ved at de har indholdet ’Valgfri gruppe’ i felt 040: ”a40 00 *a Valgfri gruppe”
Der skal ikke dannes et registerord ud fra overskriften, fordi emnet ifølge den officielle dk5, skal stå i en anden gruppe højere oppe i hierarkiet – og i øvrigt vises de fejlbehæftet. Nedenfor er 66.853 en valgfri gruppe, - og emnet, som der er søgt på, ’fiskeindustri’ står på hylden under 66.85.
Eks:
Fiskeindustri, se 66.85 Slagteri. Kød- og fiskeindustri
, se 66.853 Fiskeindustri

**Comment by KiraH** [comment]
testet OK
