### ISSUE TITLE
link til nationalbibliografiske tillægstal

### ISSUE THREAD

**Issue by KiraH** [DBCDK/tanterne#223]
Tillægstal er noget der kan tilføjes til skønlitterære klassemærker. De findes som bilag bag i tante grøn, så det naturlige vil være, at de ligger under ? i dk5pro – de almindelige brugere har ikke brug for dem. 
Det ville være smukt, hvis vi kunne linke til dem fra noten til 82-88, det er det eneste sted, der er brug for dem. Kan det lade sig gøre eller skal jeg finde en anden løsning?

**Comment by kkdbc** [comment]
vi udvider hjælpeteksten. pt. er der ingen differentiering ml. pro og ikke pro. Vi laver ikke links nu, det må være en senere fase.
