### ISSUE TITLE
Interval-grupper, som 82-88 "skjuler" grupper i intervallet

### ISSUE THREAD

**Issue by fvsdbc** [DBCDK/tanterne#251]
De øverste grupper er "kunstigt" oprettet, måske skal der tilføjes flere af disse.

Fra Birgit:

Intervalgrupperne:

Hierarkiet skabes ved at underliggende niveaus 652*j knyttes til nærmeste overordnedes 652*s:
Konstruktionen med tallet XX.9999 i 652*s er lavet for at sortere intervalklassemærket korrekt.

De øverste intervalposter findes faktisk, men jeg ved godt, at de er lavet som en tabel i dk5web på netpunkt

80-89 Litteratur. Sprog
Posten i dk5-basen: 

001 00 *a 60017328 *b 000007 *c 20111108111603 *d 19810227 *f b
004 00 *r c *x x
008 00 *t xk *v 0
652 00 *d 80-89 *u Litteratur. Sprog *s 79.9999
…. meget mere

82-88 Skønlitteratur
Posten i dk5-basen: 

001 00 *a 60014973 *b 000007 *c 20131125132605 *d 19901206 *f b
004 00 *r c *x x
008 00 *t xk *v 0
652 00 *m 82-88 *u Skønlitteratur *s 81.9999 *j 79.9999
…. meget mere

82 Fransk skønlitteratur
Posten i dk5-basen:

001 00 *a 60015791 *b 000007 *c 20020307 *d 19810311 *f b
004 00 *r c *x x
008 00 *t xk *v 0
652 00 *m 82 *u Fransk skønlitteratur *s 82 *j 81.9999

	Herfra virker det	82.5 Katalansk skønlitteratur
Posten i dk5-basen:

001 00 *a 60015449 *b 000007 *c 20020307 *d 19900302 *f b
004 00 *r c *x x
008 00 *t xk *v 0
652 00 *m 82.5 *u Katalansk skønlitteratur *s 82.5 *j 82
…. meget mere

Og så listen over problemets ikke så store omfang:
82-88
Og 
78.3-78.8
78.4-78.5
78.42-78.43
78.44-78.49
78.61-78.63

Der er andre intervalgrupper, men de fungerer, fordi der ikke er poster der peger på dem. 

Det korrekte musikhierarki ser således ud (i uddrag)

70-79 Kultur. Kunstarter sport  (652s 69.9999)
	78 Musik (652 *s 78 *j 69.9999)
		78.01 Musikfilosofi (652 *s 78.01 *j 78)
		…
		78.1 Musikteori (652 *s 78.1 *j 78)
		78.2 Musikudøvelse. Musikinstrumenter (652 *s 78.2 *j 78)
		78.3-78.8 Musikalier og musikoptagelser (652 *s 78.29999 *j 78)
				78.3 Antologi…(652 *s 78.3 *j 78.29999)
				78.4-78.5 Instrumentalmusik (652 *s78.39999 *j 78.29999)
					78.4 Instru…(652 *s 78.4 *j 78.39999)
					78.5 … tangent… (652 *s 78.4 *j 78.39999) 
					78.5 var faktisk forkert i basen den havde *j78.2999

				78.6 Vokalmusik (652 *s 78.6 *j 78.29999)
					78.61-78.63 Vokal (*s 78.609999 *j 78.6)
						78.61 (*s 78.61 *j 78.609999)
					78.65 Kormusik (*s 78.5 *j 78.6)
					…

				78.7 Folkemusik…. (652 *s 78.7 *j 78.29999)
				78.8 Scenisk musik (652 *s 78.8 *j 78.29999)
		78.9 Musikhistorie (652 *s 78.9 *j 78)

**Comment by BirgitG** [comment]
Du må vurdere, om der skal laves kunstige grupper af de få øvrige intervalgrupper, der er nødvendige. Forskellen på disse og de øverste intervalgrupper er at de har nogle af systemets længste noter, hvorimod topgrupperne højst har en historisk note om en tidligere formulering af overskriften. (Disse note kommer i øvrigt ikke med ud ved søgning, sandsynligvis fordi ikke er i de kunstigt oprettede grupper, men det er ikke et kardinalpunkt).
Kan det løses ved at jeg retter sorteringsfelterne dvs felterne hvor tallet ender på '9999' til noget det 'intervallet' uden at det går ud over sorteringen???? '9999' har jo været brugt til at styre sorteringen, så fx 82-88 kom før 82 i trykte udgaver og dk5web, men kan det styres anderledes nu????

**Comment by fvsdbc** [comment]
Prøver i første omgang at tilføje den til den interne interval-liste. Herved hænger det interne hierarki sammen.
