### ISSUE TITLE
Hvis der ikke er et felt 652*m, skal der ikke stå noget efter opslagsordet

### ISSUE THREAD

**Issue by KiraH** [DBCDK/tanterne#269]
Hvis der ikke er et felt 652*m, skal der ikke stå noget efter opslagsordet – Det kan være ret misvisende, hvis der bare henvises til klassemærket for det første aspekt. I nedenstående eksempel skal ”, se 22.08” altså fjernes, - det er jo en relativt begrænset del af litteraturen om Israel, som står under 22.08 Bibelske hjælpevidenskaber i alm. 

Israel, se 22.08 
-	Bibelsk arkæologi, se 22.08 Bibelske hjælpevidenskaber i alm.
-	Geografi, se 48.22 Israel
-	Historie, se 98.22 Israels historie. Palæstinas historie
-	Kunsthistorie i alm., se 70.9822

**Comment by fvsdbc** [comment]
Overgrupper er karakteriseret ved ikke at have noget 652m, men istedet b52m, som gentages. Så løsningen er nok så "simpel" som at fjerne klassemærke, link og til-kurv-ikon fra disse

**Comment by fvsdbc** [comment]
Fixed
