### ISSUE TITLE
der mangler generelle henvisninger fra felt b00*a og *b

### ISSUE THREAD

**Issue by KiraH** [DBCDK/tanterne#270]
Der mangler de generelle henvisninger som ligger i felt b00*a og *b

I Tantedigital:
Italiensk skønlitteratur, se 82.6 Italiensk skønlitteratur

I Tanteanalog:
Italiensk skønlitteratur 82.6
-	Italiensk skønlitteratur oversat til dansk må søges i den alfabetiske forfatter- og titelkatalog

**Comment by fvsdbc** [comment]
Det er som aftalt i sin tid. Klikker man på 82.6, så ser man den anførste note. Søg fx. på jargon, hvor noten før klik, netop er anderledes end den efter klik. Det er muligt at vi har snakket forbi hinanden i sin tid.

**Comment by fvsdbc** [comment]
"italiensk skønlitteratur" skal have noten: " - Italiensk skønlitteratur oversat til dansk må søges i den alfabetiske forfatter- og titelkatalog" tilføjet på søgeresultatet, så det kan ses med det ikke og ikke "gemmes" under videreklikket

**Comment by fvsdbc** [comment]
Fixed
