### ISSUE TITLE
migræne henviser til 61.641, men 61.641 henviser ikke til migræne

### ISSUE THREAD

**Issue by KiraH** [DBCDK/tanterne#272]
Hvis man søger på migræne henvises korrekt kun til 61.641, men migræne er ikke blandt de i alt 51 emner, der er nævnt, når man går ind under 61.641 – og når jeg tæller emnerne i den analoge udgave tante lilla, er der 58 emner under 61.641. Der mangler også noget i 61.642, men je har også fundet en del grupper, hvor listen er komplet – mystisk???

**Comment by fvsdbc** [comment]
Underligt. Min lokale version viser en smule andet en drift-versionen. Heriblandt migræne.

**Comment by fvsdbc** [comment]
Har prøvet at lave et nyt dump og konvertere det og ind i min elastic. Migræne er der som det skal være. Så hvorfor der er forskel på det jeg gør og det der ses i drift ved jeg ikke. Er det et "gammelt" dump der bruges eller loades?

**Comment by fvsdbc** [comment]
Data er det samme på stg som lokalt på min PC, men alligevel er resultatet forskelligt når der søges. Byggejob'et havde en fejl, men det forandrer desværre ikke på resultatet. Så, koden er identisk, det der loades i ES er identisk, men resultatet er ikke. Kigger videre senere.

**Comment by fvsdbc** [comment]
Elastic search versionen på staging og drift er pænt gamle. Prøver at få dem opversioneret, eftersom de, med samme data som udviklingsmaskinen, giver forkert resultat.

**Comment by fvsdbc** [comment]
Kan lukkes
