### ISSUE TITLE
 Visning af 652*d

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/tanterne#414]
En søgning på ’tidsskrifter’ viser i listen, at det findes, men kan alligevel ikke søges

Måske fordi 652*d ikke vises i resultatet. 652*d indeholder et ”fra-til”-klassemærke.

Siden da er registerposten i dk5-basen rettet, så nu ser opslaget i tantedigital således ud:

- Tidsskrifter, se 07.8 
- Tidsskrifter af blandet indhold, se 07.8 Presse

Hvilket må siges at være en stærkt manipuleret og misvisende gengivelse af dk5-posten (relevante felter):
- 630 00 *a Tidsskrifter
- b00 00 *a Emnemæssigt afgrænsede tidsskrifter må søges under emnet
- b52 00 *å 1 *y Tidsskrifter af blandet indhold *d 05.2-05.8975
- b52 00 *å 2 *y Publicering *m 07.8

**Comment by fvsdbc** [comment]
Noten fra b00 *a skal tilføjes på søgeresultatet, som en selvstændig pind under 630 *a

**Comment by fvsdbc** [comment]
652 *d alternativt b52 *d, skal vises i stedet for 07.8

**Comment by fvsdbc** [comment]
Et andet eksempel på det samme, kan ses ved søgning på kriser

**Comment by fvsdbc** [comment]
Lukkes efter aftale med Birgit
