### ISSUE TITLE
DK5 intervaller

### ISSUE THREAD

**Issue by fvsdbc** [DBCDK/tanterne#457]
Problem nr. 1
Det ser ud som om intervaller, som kommer fra 652*d i datagrundlaget ikke vises. Det er svært at finde eksempler på, så du får kun dette ene
630 00 *a Nationalregnskaber
652 00 *d 33.181-33.1895
b52 00 *å 1 *y Nationalregnskabsteori *m 33.1
b52 00 *å 2 *y Statsregnskab *m 33.78
b52 00 *å 3 *y Danmark *m 33.19
d09 00 *a REK199201

Nationalregnskaber burde stå her- Deleøkonomi på enkelte områder sættes under emnet
* Danmark, se 33.19 Danmarks økonomiske forhold i alm.
*  Nationalregnskabsteori, se 33.1 Økonomiske systemer. Produktionsfaktorerne og prisdannelsen
* Statsregnskab, se 33.78 Statsregnskab og statsbudget

Problem nr. 2 – denne fejl vildleder brugerne
Der byttes rundt på henvisningerne til de enkelt underpinde under emneordene, når en af pindene henviser til et interval.
Det er ’tidsskrift’-problemet i en lidt ny variation. Jeg har forsøgt at analysere, hvad der sker undervejs fra mit datagrundlag i DBCkat til visningen i dk5pro. Jeg ved, at datagrundlaget manipuleres undervejs fra DBCkat til dk5pro, men jeg ved ikke hvor i processen fejlen sker. 
Fundamentalt er problemet, at tekst og klassemærke inden for 1 b52-felt, skilles ad, men de skal forblive sammen.
Det der sker er, at uanset hvilket nummer b52, der henviser til et interval, så vises intervallet i tilknytning til det b52-felt, som har å1. Hvis det så ikke er b52*å1, som henviser til intervallet, så forsvinder det klassemærke, som b52*å1 henviser til ud af sagaen. Herefter hentes b52-felterne 1 ad gangen og får det første klassemærke herefter, så klassemærkerne rykker 1 plads opad i forhold til datagrundlaget fra DBCkat. Til sidst er der så et b52-felt til overs, men da det første klassemærke er smidt væk er der ikke noget klassemærke til dette felt, og derfor slettes det.
Nedenfor har jeg markeret i DBC-katposten, hvad der er ændret i de eksempler jeg har set på for at finde et mønster i fejlen.
DBC-kat:
630 00 *a Regionalpolitik
652 00 *m 33.106
b51 00 *å 3 *a Før 2007: *b 33.26:65 – denne note vises ikke, da b52*å3, som den knytter sig til, slettes
b52 00 *å 1 *y Andre lande *d 33.181-33.1895 – det står korrekt, da det knytter sig til b52 *å1
b52 00 *å 2 *y Danmark *m 33.19
b52 00 *å 3 *y EU *m 33.2665

DK5pro:
Regionalpolitik, se 33.106 
Andre lande, se 33.181-33.1895 Enkelte områders, landes og lokaliteters økonomiske geografi og historie i alm.
Danmark, se 33.2665 EU's økonomiske samarbejde i alm.

DBC-kat:
630 00 *a Kriser *e økonomiske 
b52 00 *å 1 *y Økonomiske svingninger *m 33.27 
b52 00 *å 2 *y Andre landes økonomiske forhold i alm. *d 33.181-33.1895 
b52 00 *å 3 *y Danmarks økonomiske forhold i alm *m 33.19

DK5pro:
Kriser (økonomiske)
* Andre landes økonomiske forhold i alm., se 33.19 Danmarks økonomiske forhold i alm.
* Økonomiske svingninger, se 33.181-33.1895 Enkelte områders, landes og lokaliteters økonomiske geografi og historie i alm.

DBC-kat:
630 00 *a Urbanisering
b52 00 *å 1 *y Sociologi *m 30.14
b52 00 *å 2 *y Bebyggelsesgeografi *m 71.9
b52 00 *å 3 *y Økonomisk udvikling og vækst *m 33.106
b52 00 *å 4 *y Økonomisk udvikling og vækst, enkelte lande *d 33.181-33.19 

Her flyttes klassemærkerne ikke opad, da det er sidste b52 felt, som henviser til et interval, men intervallet flyttes bare op som henvisning for Sociologi, som har b52*å1 og sidste pind forsvinder

DK5pro:
Urbanisering
* Bebyggelsesgeografi, se 71.9 Bebyggelse
* Sociologi, se 33.181-33.19
* Økonomisk udvikling og vækst, se 33.106 Økonomisk udvikling og vækst

DBC-kat:
630 00 *a Cellomusik
b52 00 *å 1 *y Kammermusik *d 78.42-78.43
b52 00 *å 2 *y Koncerter *m 78.412:44
b52 00 *å 3 *y Skoler *m 78.44401
b52 00 *å 4 *y Solo *m 78.444

DK5pro:
Cellomusik
* Kammermusik, se 78.42-78.43 Kammermusik
* Koncerter, se 78.44401
* Skoler, se 78.444 Violoncel

**Comment by fvsdbc** [comment]
Mail fra Birgit:
"Jeg har i forståelse med Per og Carsten rettet et par hundrede dk5-registerposter, så der ikke længere burde forekomme *d som formattering af intervalklassemærket. Det betyder, at problemet med dk5 og intervaller er udyddet, og kan slettes fra listen. "

Kanske at dette issue derfor kan lukkes?

**Comment by BettinaAndersen** [comment]
Lukkes grundet ovenstående mail fra Birgit
