### ISSUE TITLE
Billede-links virker ikke i IE-browser

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/tanterne#501]
Ved klik på billede på forsiden skifter url'en korrekt, men siden loades ikke. (Ved reload af siden skiftes til den rigtige side).

**Comment by fvsdbc** [comment]
Url'en skifter og en efterfølgende reload af siden viser så det korrekte. Linket er klart ok, så måske er det en "bind" på anker elementet der mangler for at IE vil fungere.

**Comment by fvsdbc** [comment]
... og rettelsen funker alligevel ikke. Ved ikke hvorfor det virkede da Bettina og jeg testede det.

**Comment by KiraH** [comment]
testet OK
