### ISSUE TITLE
Det er ikke muligt at bruge pilene i suggester-listen i IE

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/tanterne#576]
Ved test https://github.com/DBCDK/tanterne/issues/568 er det observeret at det ikke er muligt at bruge pilene ved suggestions i søgeresultatet. Det er kun muligt at vælge noget med musen.
![image](https://user-images.githubusercontent.com/28528078/37596489-9ce84de6-2b7c-11e8-9de0-45672a2a1f56.png)

Accept: Det skal være muligt at scrolle ned og op i suggest-listen med pilene.

**Comment by KiraH** [comment]
testet done
