### ISSUE TITLE
Analyse: Forbedringsønsker DK.5

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/tanterne#582]
Vedhæftede dokument er modtager fra Birgit Gøtterup.
De skal groomes i sprint 14-15 og gerne løses i 16-17.
[Opsamling fejl til sprint i april.docx](https://github.com/DBCDK/tanterne/files/1855974/Opsamling.fejl.til.sprint.i.april.docx)

**Comment by fvsdbc** [comment]
Splitter dette issue op i de issues som dokumentet indeholder

**Comment by fvsdbc** [comment]
Udvidet til / erstattet af: #222 #265 #458 #515 #585 #586 #587 #588 #589
