### ISSUE TITLE
Cursor placering (dk5 og pro)

### ISSUE THREAD

**Issue by fvsdbc** [DBCDK/tanterne#588]
Når man er i hierarkiet er cursoren ikke placeret nogen steder.
Det ville være godt, hvis den automatisk stod i søgefeltet klar til en ny søgning. Hvis man skal videre ned i hierarkiet, skal man jo alligevel selv klikke der, hvor man vil hen.

Når man søger alfabetisk står cursoren efter søgeordet – det er godt, hvis man skal bygge videre på søgeordet. Det ville være godt, at kunne slette ordet let f.eks. ved at trykke på et X i slutningen af linien eller det var markeret, så man bare kunne skrive på ny. Pt kan man starte forfra ved klik på titlen ’DK5 PRO’/’Find en bog med DK5’, men det var nok mere tydeligt for brugerne med et kryds eller lignende.

**Comment by KiraH** [comment]
testet OK
