### ISSUE TITLE
Tøm indkøbskurv (kun pro)

### ISSUE THREAD

**Issue by fvsdbc** [DBCDK/tanterne#589]
Savner at kunne tømme indkøbsvognen, uden at slette søgningen – fra søgebjælken kan man søge igen uden at slette indkøbsvognen, men det modsatte, altså at tømme indkøbsvognen uden at slette søgningen – og uden at skulle slette indholdet én ad gangen, kunne også være godt.  KAN NU GØRES MED GENVEJSTASTER - IKON ØNSKES STADIGT

**Comment by KiraH** [comment]
testet OK
