### ISSUE TITLE
nye tillægstal og rettelser til vejledning

### ISSUE THREAD

**Issue by KiraH** [DBCDK/tanterne#626]
teksten om tillægstal for skønlitteratur skal ændres:

Dansk Bogfortegnelses tillægstal

Dansk bogfortegnelse anvender ved underdeling af skønlitteraturen et system af tillægstal, som adskilles fra det egentlige klassemærke ved en kort streg. Disse tal bruges i stedet for decimalerne 1 og 2, hvis anvendelse i decimalklassedelingen er beskrevet i noten til 82-88. Tillægstallene vil kunne finde anvendelse også ved anden bibliografisk systematik over skønlitteratur.

Tillægstallene for skønlitteratur består af to eller tre cifre, hvoraf det første angiver publiceringssproget, og det andet og tredje dels angiver digtarten, dels markerer antologiform.

1. ciffer tildeles efter nedenstående tabel:

0  Skrifter på originalsproget
1  Skrifter oversat til fremmesprog
2  Skrifter oversat til dansk

2.-3. ciffer tildeles efter nedenstående tabel
0  Digte. Antologier
(0	udelades ikke, selv om det er sidste ciffer). Vise- og sangbøger sættes i 78.69 eller 79.7.
1  Digte. Værker af enkelte forfattere
Tillægstallene 0 og 1 omfatter ikke episk og dramatisk litteratur på vers. Kortere fortællende digte placeres dog i formgrupperne 0 og 1.

2  Skuespil. Antologier
3  Skuespil. Værker af enkelte forfattere
4  Romaner og noveller. Antologier
Her anbringes også antologier, sammensat af forskellige digtarter.
I grupperne 86 og 88 placerer bogfortegnelsen læsebøger og prosaantologier til skolebrug i en undergruppe med tillægstallet -046 eller -246. Andre Skoleudgaver af skønlitteratur placeres som tilsvarende alm. udgaver. 
5 Romaner og noveller før 1901. Værker af enkelte forfattere
6  Romaner og noveller. 1901-. Værker af enkelte forfattere
7  Humor, tegneserier etc. Antologier
Her anbringes samlinger af vittigheder og humoristiske småstykker. 
Vittighedstegninger sættes i 72 eller 74.91 med undergrupper.
8  Humor, tegneserier etc. af enkelte forfattere
9  Børne- og ungdomsbøger
90 Digte for børn. Antologier
91 Digte for børn. Enkelte forfattere
92 Børnekomedier. Antologier
93 Børnekomedier. Enkelte forfattere
94 Fortællinger for børn. Antologier 
	Her anbringes også antologier sammensat af forskellige digtarter.
96 Fortællinger for børn. Enkelte forfattere
97 Humor, tegneserier etc. for børn. Antologier
98 Humor, tegneserier etc. for børn. Enkelte forfattere

**Comment by fvsdbc** [comment]
Close
