### ISSUE TITLE
kurv funktion

### ISSUE THREAD

**Issue by vibjerg** [DBCDK/tanterne#88]
Der skal være muligt at se en oversigt med de valgte poster.

Man skal kunne fjerne en eller alle poster fra oversigten

**Comment by vibjerg** [comment]
![img_0850](https://cloud.githubusercontent.com/assets/1691725/24345822/27a48694-12d2-11e7-93e3-4774685b1f68.jpg)
![img_0849](https://cloud.githubusercontent.com/assets/1691725/24345823/27b8981e-12d2-11e7-9ef8-530b8c09601a.jpg)

**Comment by KiraH** [comment]
Jeg kan tilføje poster til kurven og fjerne dem, forstået på den måde at tallet i kurven ændrer sig.

Jeg kan dog ikke se posterne. Der sker ikke noget hvis jeg klikker på kurven.

Hvis jeg går ud på forsiden bliver tallet på kurven sat til 0.

**Comment by hrmoller** [comment]
@KiraH Jeg har skåret det en lille smule anderledes så denne issue har været af overvejende teknisk karakter. Visning og toggle kurv til/fra kommer med #85

**Comment by KiraH** [comment]
OK, så lukker jeg denne igen.
