### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by vibjerg** [DBCDK/tanterne#92]
Tekster skrives af ES og MDY

**Comment by kkdbc** [comment]
copyright dbc 2017

**Comment by kkdbc** [comment]
fx copyright (altså copyright-tegnet) DBC as, Tempovej 7-11, DK-2750 Ballerup, +45 44 86 77 11, link til Kundeservice.dbc.dk

**Comment by kkdbc** [comment]
teksten skal rettes til 2017
